package main

import (
	"log"
	"os"

	"github.com/gin-gonic/gin"
	"github.com/jixlox0/studoto-backend/internal/config"
	"github.com/jixlox0/studoto-backend/internal/database"
	"gorm.io/gorm"
)

// App holds the application dependencies.
// This struct is used by Wire to inject all dependencies.
type App struct {
	Router *gin.Engine
	DB     *gorm.DB
}

// NewApp creates a new App instance.
// This function is used by Wire as a provider to construct the App.
func NewApp(router *gin.Engine, db *gorm.DB) *App {
	return &App{
		Router: router,
		DB:     db,
	}
}

func main() {
	// Load configuration
	cfg, err := config.Load()
	if err != nil {
		log.Fatalf("Failed to load configuration: %v", err)
	}

	// Initialize application using Wire dependency injection
	// InitializeApp is generated by Wire in wire_gen.go
	app, err := InitializeApp(cfg)
	if err != nil {
		log.Fatalf("Failed to initialize application: %v", err)
	}

	// Get underlying sql.DB for proper connection closing
	sqlDB, err := app.DB.DB()
	if err != nil {
		log.Fatalf("Failed to get database instance: %v", err)
	}
	defer sqlDB.Close()

	// Run migrations
	if err := database.RunMigrations(app.DB); err != nil {
		log.Fatalf("Failed to run migrations: %v", err)
	}

	// Start server
	port := os.Getenv("PORT")
	if port == "" {
		port = "8080"
	}

	log.Printf("Server starting on port %s", port)
	if err := app.Router.Run(":" + port); err != nil {
		log.Fatalf("Failed to start server: %v", err)
	}
}
