// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/jixlox0/studoto-backend/internal/api"
	"github.com/jixlox0/studoto-backend/internal/config"
	"github.com/jixlox0/studoto-backend/internal/database"
	"github.com/jixlox0/studoto-backend/internal/middleware"
	"github.com/jixlox0/studoto-backend/internal/repository"
	"github.com/jixlox0/studoto-backend/internal/service"
	"github.com/jixlox0/studoto-backend/pkg/auth"
	"github.com/jixlox0/studoto-backend/pkg/cache"
	"github.com/jixlox0/studoto-backend/pkg/oauth"
)

// Injectors from wire.go:

// InitializeApp initializes the application with all dependencies using Wire.
// This function is used by Wire to generate the dependency injection code.
// The generated code will be in wire_gen.go
func InitializeApp(cfg *config.Config) (*App, error) {
	databaseConfig := provideDatabaseConfig(cfg)
	db, err := database.NewConnection(databaseConfig)
	if err != nil {
		return nil, err
	}
	userRepository := repository.NewUserRepository(db)
	string2 := provideJWTSecretKey(cfg)
	int2 := provideJWTExpirationHours(cfg)
	redisConfig := provideRedisConfig(cfg)
	client, err := cache.NewRedisClient(redisConfig)
	if err != nil {
		return nil, err
	}
	tokenCache := cache.NewRedisCache(client)
	jwtAuth := auth.NewJWTAuth(string2, int2, tokenCache)
	userService := service.NewUserService(userRepository, jwtAuth)
	oAuthConfig := provideOAuthConfig(cfg)
	oAuthService := oauth.NewOAuthService(oAuthConfig)
	authService := service.NewAuthService(userRepository, jwtAuth, oAuthService)
	authMiddleware := middleware.NewAuthMiddleware(jwtAuth)
	handlers := api.NewHandlers(userService, authService, authMiddleware)
	engine := api.NewRouter(handlers, cfg)
	app := NewApp(engine, db)
	return app, nil
}

// wire.go:

// provideDatabaseConfig extracts the database configuration from the main config.
func provideDatabaseConfig(cfg *config.Config) config.DatabaseConfig {
	return cfg.Database
}

// provideJWTSecretKey extracts the JWT secret key from the config.
func provideJWTSecretKey(cfg *config.Config) string {
	return cfg.JWT.SecretKey
}

// provideJWTExpirationHours extracts the JWT expiration hours from the config.
func provideJWTExpirationHours(cfg *config.Config) int {
	return cfg.JWT.ExpirationHours
}

// provideOAuthConfig extracts the OAuth configuration from the main config.
func provideOAuthConfig(cfg *config.Config) config.OAuthConfig {
	return cfg.OAuth
}

// provideRedisConfig extracts the Redis configuration from the main config.
func provideRedisConfig(cfg *config.Config) cache.RedisConfig {
	return cache.RedisConfig{
		Host:     cfg.Redis.Host,
		Port:     cfg.Redis.Port,
		Password: cfg.Redis.Password,
		DB:       cfg.Redis.DB,
	}
}
